FUNCTION(AddSrc SRCLIST FILEPATH)
	SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        SET(TMPSRCLIST ${argvalue})
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST}")		
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${SRCLIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${SRCLIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDFUNCTION(AddSrc)

FUNCTION(AddSrcWin32 SRCLIST FILEPATH)
IF(WIN32)
	SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        SET(TMPSRCLIST ${argvalue})
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST}")		
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${SRCLIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${SRCLIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcWin32)

FUNCTION(AddSrcLinux SRCLIST FILEPATH)
IF(UNIX AND NOT APPLE)
	SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        SET(TMPSRCLIST ${argvalue})
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST}")		
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${SRCLIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${SRCLIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcLinux)

FUNCTION(AddSrcApple SRCLIST FILEPATH)
IF(APPLE)
	SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        SET(TMPSRCLIST ${argvalue})
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST}")		
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${SRCLIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${SRCLIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcApple)

FUNCTION(AddSrcAndroid SRCLIST FILEPATH)
IF(ANDROID)
	SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        SET(TMPSRCLIST ${argvalue})
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST}")		
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${SRCLIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${SRCLIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcAndroid)

#------------------------------------------------------------------

FUNCTION(AddSrcDir FILELIST PATHLIST)
    SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        AUX_SOURCE_DIRECTORY(${argvalue} TMPSRCLIST)
	    INCLUDE_DIRECTORIES(${argvalue})
	    SET(TMPFILELIST)
	    FILE(GLOB TMPFILELIST ${argvalue}/*.h)
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST};${TMPFILELIST}")
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${FILELIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${FILELIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDFUNCTION(AddSrcDir)

FUNCTION(AddSrcDirWin32 FILELIST PATHLIST)
IF(WIN32)
    SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        AUX_SOURCE_DIRECTORY(${argvalue} TMPSRCLIST)
	    INCLUDE_DIRECTORIES(${argvalue})
	    SET(TMPFILELIST)
	    FILE(GLOB TMPFILELIST ${argvalue}/*.h)
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST};${TMPFILELIST}")
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${FILELIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${FILELIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcDirWin32)

FUNCTION(AddSrcDirLinux FILELIST PATHLIST)
IF(UNIX AND NOT APPLE)
    SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        AUX_SOURCE_DIRECTORY(${argvalue} TMPSRCLIST)
	    INCLUDE_DIRECTORIES(${argvalue})
	    SET(TMPFILELIST)
	    FILE(GLOB TMPFILELIST ${argvalue}/*.h)
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST};${TMPFILELIST}")
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${FILELIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${FILELIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcDirLinux)

FUNCTION(AddSrcDirApple FILELIST PATHLIST)
IF(APPLE)
    SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        AUX_SOURCE_DIRECTORY(${argvalue} TMPSRCLIST)
	    INCLUDE_DIRECTORIES(${argvalue})
	    SET(TMPFILELIST)
	    FILE(GLOB TMPFILELIST ${argvalue}/*.h)
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST};${TMPFILELIST}")
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${FILELIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${FILELIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcDirApple)

FUNCTION(AddSrcDirAndroid FILELIST PATHLIST)
IF(ANDROID)
    SET(TMPLIST)
	LIST(LENGTH ARGV argc)
    SET(i 1)
	WHILE(i LESS ${argc})	    
	    LIST(GET ARGV ${i} argvalue)  
        SET(TMPSRCLIST)
        AUX_SOURCE_DIRECTORY(${argvalue} TMPSRCLIST)
	    INCLUDE_DIRECTORIES(${argvalue})
	    SET(TMPFILELIST)
	    FILE(GLOB TMPFILELIST ${argvalue}/*.h)
		SET(TMPLIST "${TMPLIST};${TMPSRCLIST};${TMPFILELIST}")
		MATH(EXPR i "${i} + 1")
    ENDWHILE()
	LIST(GET ARGV 0 argvalue) 
	IF("X${${argvalue}}" EQUAL "X")
	    SET(${FILELIST} "${TMPLIST}" PARENT_SCOPE)
	ELSE()
	    SET(${FILELIST} "${${argvalue}};${TMPLIST}" PARENT_SCOPE)
	ENDIF()
ENDIF()
ENDFUNCTION(AddSrcDirAndroid)
